name: 'Run Unit tests'
description: 'Will run unit tests via QUnit'

runs:
  using: "composite"
  steps:
    - name: Run Unit tests
      shell: bash
      run: |
        echo 'Running unit tests'
        npm run test:unit

    - name: Store Unit test reports
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: qunit-reports
        path: |
          .nyc_output/
        retention-days: 30

