name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
    types: [ opened, review_requested, edited, reopened ]
    paths: [ 'src/**', 'tests/**' ]
  workflow_dispatch:
    inputs:
      appName:
        description: 'Name of the app being deployed'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      commitName:
        description: 'Commit message'
        required: false
        default: ${{ github.event.head_commit.message }}
        type: string
      commitKey:
        description: 'Unique key for cache'
        required: false
        default: ${{ github.event.pull_request.head.sha }} #"${{ github.head_ref }}.${{ github.sha }}"
        type: string

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest # runs-on: self-hosted, ubuntu-latest, macos-latest, windows-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
        projects: [ chromium ]
        os: [ ubuntu ] # ubuntu windows macos
        chrome-version: [ canary ] # latest, stable, beta, dev, canary or number like: 119 or 120.0.6099 (https://googlechromelabs.github.io/chrome-for-testing/)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
          fetch-depth: 0

      - name: setup node and package manager
        uses: ./.github/actions/setup-node
        with:
          version: '${{ matrix.node-version }}'
          key: '${{ inputs.commitKey }}'
          pkg-manager: 'npm'

      - name: build component
        uses: ./.github/actions/build-component

  test:
    timeout-minutes: 60
    needs: [build]
    runs-on: ubuntu-latest
    steps:
#      - name: Run unit test
#        uses: betajs/betajs-media-components/.github/actions/unit-test@main
      - name: Run playwright tests
        uses: ./.github/actions/playwright-test
        with:
          project: ${{ matrix.projects }}
          port: 5050

#  deploy:
#    needs: [build, test]
#    runs-on: ubuntu-latest
#    name: 'Deploy to npm'
#    steps:
#      - uses: actions/checkout@v3
